version: '3'

services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - mysql
  
  mysql:
    image: mysql:5.7
    ports:
      - 33060:3306
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sensey12
      - MYSQL_DATABASE=punisher__db
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=sensey12

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data
    ports:
      - 6379:6379


volumes:
  mysqldata:
  
#  es01:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
#    container_name: es01
#    environment:
#      - cluster.initial_master_nodes=es01
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    ports:
#      - 9200:9200