<?php

namespace tests\unit\fixtures;

use app\modules\user\v1\models\Token;
use app\modules\user\v1\models\User;
use app\modules\violation\v1\models\Violation;
use Faker\Factory;
use yii\test\ActiveFixture;

class UserFixture extends ActiveFixture
{
    public $modelClass = User::class;

    public function beforeLoad()
    {
        Token::deleteAll();
        parent::beforeLoad(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     * @throws \yii\base\Exception
     * @throws \yii\base\InvalidConfigException
     */
    public function getData()
    {
        $data = [];
        $datetime = \Yii::$app->formatter->asDatetime(time());
        $faker = Factory::create();

        for ($i = 0; $i < 12; $i++) {
            $user = new User();
            $user->username = $faker->name;
            $user->email = $faker->email;
            $user->status = 10;
            $user->generateAuthKey();
            $user->generatePasswordResetToken();
            $user->setPassword('sensey12');
            $user->updated_at = $datetime;
            $user->created_at = $datetime;
            $data[] = $user->getAttributes();
        }
        return $data;
    }
}